services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://72.61.228.9:8060
    ports:
      - "8070:8070"
    restart: always
    container_name: vertical-pulse-frontend
