services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "8070:80"
    restart: always
    container_name: vertical-pulse-frontend
